description: >
  An archive of works about anarchism, linguistics, philosophy, physics,
  psychology, and more.
kramdown:
  syntax_highlighter_opts:
    disable: false
  footnote_backlink: '&#x21A9;&#xFE0E;'
  remove_line_breaks_for_cjk: true
lang: en_US
logo: /assets/img/me.jpg
markdown: kramdown
paginate: 10
paginate_path: /archive/:num
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-titles-from-headings
repository: una-ada/anarchy.website
sass:
    sass_dir: _sass
social:
  name: Una Ada
  links:
    - https://github.com/una-ada
    - https://twitter.com/unaxiii
theme: jekyll-theme-minimal
title: anarchy.website
twitter:
  username: unaxiii
url: https://anarchy.website
